name: for_kids
description: A new Flutter project for kids.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.0.3

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.9
  svg_path_parser: ^1.1.1
  path_provider: ^2.1.2
  image: ^4.1.7
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/area_color/
    - assets/free_color/